### ISSUE TITLE
fossa-cli should not consider contents of go.sum

### ISSUE THREAD

**Issue by imjasonh** [fossas/fossa-cli#1008]
In the Go modules ecosystem, a `go.mod` file lists current direct and indirect dependencies of the module. A `go.sum` file includes information about modules@versions that have ~ever been seen during the history of a module, and those modules@verisons' hashes.

The purpose of `go.sum` is to detect scenarios where a module@version has an unexpected new hash, when it had previously been seen with a different hash (`go.sum` records the previous hash). It's valid (though slightly less secure) to delete a module's `go.sum` file, and it doesn't affect the correctness of the build, so long as a dependency module@version isn't compromised.

The presence of a dependency in `go.sum` does not indicate that the module depends on that module. 

However, FOSSA seems to consider the contents of `go.sum` when building its dependency graph, here:

https://github.com/fossas/fossa-cli/blob/7013d3b0203df9e648cd25466cac4913e54452cc/analyzers/golang/analyze.go#L61-L66

This leads to false positives, and unnecessary questions from users of a module who can't be sure from FOSSA's output whether a module depends on something or not (e.g., https://github.com/google/go-containerregistry/issues/1422).

I'd like to recommend removing the code section above, and only consider the contents of `go.mod` when building FOSSA's dependency graph. I'd be happy to send a PR to make this change if that's acceptable.

Ref:
- https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using

**Comment by zlav** [comment]
Hi @imjasonh! Thank you for opening this detailed ticket. The code you referenced is in a deprecated version of the FOSSA-CLI and was used as a backup strategy if a `go.mod` file could not be parsed. I recommend that you update to the latest version of the FOSSA CLI, which has better overall support for Golang analysis and will ensure that you get any of the updates we release.

I am going to close this ticket as it is for a deprecated version of the CLI that we are not planning on making modifications to.

**Comment by scruffystuffs** [comment]
This code snippet looks to be from version 1.x.  That version of the code is deprecated and we will not release any fixes to it.  

I suggest migrating to 3.x, using [this migration guide](https://github.com/fossas/fossa-cli/blob/master/docs/differences-from-v1.md).

In versions >= 2.x, we do not use `go.sum` to identify golang dependencies.

Closing as we will not provide any updates to this branch of the code.

**Comment by ItalyPaleAle** [comment]
Hi @zlav thanks for the response. We (dapr/dapr) reported the original issue. We are running FOSSA scans using the official Action `fossas/fossa-action` which we thought was using the last version of the CLI (we pinned v1.1.0 of the Action if that matters).

Could you please let us know what version of the CLI we should be using, and if there's something specific we need to do with the Action?

**Comment by zlav** [comment]
Linking my response in the original issue for posterity: https://github.com/google/go-containerregistry/issues/1422#issuecomment-1201521352

I would recommend using the latest version, which is currently v3.3.11. I don't believe there is anything additional you need to do with the GitHub action

**Comment by ItalyPaleAle** [comment]
Thanks @zlav  and @imjasonh . We will follow-up with FOSSA support.

**Comment by shubham1172** [comment]
FYI, the FOSSA action from Dapr/Dapr is using FOSSA CLI version 3.3.11 (revision 8b486da23adf compiled with ghc-9.0).
