### ISSUE TITLE
What is the FOSSA_API_KEY thats referenced in the documentation?

### ISSUE THREAD

**Issue by sbtaylor15** [fossas/fossa-cli#103]
Do I need a key and if so how do I get one?

**Comment by ilikebits** [comment]
You only need a key to use https://app.fossa.io in conjunction with the FOSSA CLI (we call this feature [Provided Builds](https://fossa.io/docs/getting-started/provided-builds/)) to upload your analysis results.

Actions that DO NOT require a key:
- `fossa init`: autoconfigure modules for the FOSSA CLI to analyse
- `fossa analyze --output`: run an analysis, and output the results
- `fossa report`:  generate a list of licenses used by your project's dependencies
- `fossa report --type=dependencies`: generate a list of dependencies used by your project
- `fossa build`: build your project (assuming it's set up to use the conventions of its build system e.g. `npm install`)
- `fossa update`: update to the latest version of `fossa`

Actions that DO require a key:
- `fossa analyze`: runs and uploads an analysis to FOSSA, so we can check the results against your project's policy
- `fossa test`: check for issues with your project (e.g. licensing problems) as defined by your project's FOSSA policy
- `fossa upload`: upload custom analysis results to FOSSA (for complicated build systems)

You can get a key by signing up for an account at https://fossa.io, and then generating a key at Account Settings (in the top right user menu) > Integrations > API.

Does this help answer your question?

**Comment by sbtaylor15** [comment]
Yes.  Thanks for the clarification.
