### ISSUE TITLE
Release as docker image

### ISSUE THREAD

**Issue by 6543** [fossas/fossa-cli#1039]

**Comment by scruffystuffs** [comment]
We have no plans to release `fossa-cli` as a docker image at this time.

If you need to include it in your own docker image, you can do so by adding the installation instructions as RUN directives in your `Dockerfile`.  For example, to fetch the latest version of `fossa` on every build:
```dockerfile
RUN curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
```

Please see our installation instructions [here](https://github.com/fossas/fossa-cli#using-the-install-script) for more options on installing to fit your needs.
