### ISSUE TITLE
Generate debian copyright file

### ISSUE THREAD

**Issue by bpicode** [fossas/fossa-cli#108]
Hi,

it would be cool if one could use `fossa-cli` to write the debian copyright file. This file has a [suggested format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) and is part of the [debian policy](https://www.debian.org/doc/debian-policy/#copyright-information/).

Best regards

**Comment by ilikebits** [comment]
Cool, this sounds like a great idea. We'll put this on our roadmap, and PRs are welcome.

**Comment by zlav** [comment]
Hi @bpicode, this feature no longer aligns with the purpose of the fossa-cli, which focuses on identifying dependencies and scanning them. If that changes in the future then maybe this will be added to our roadmap, but for now I am going to close this issue.
