### ISSUE TITLE
Support OpenBSD-adJ/amd64

### ISSUE THREAD

**Issue by vtamara** [fossas/fossa-cli#1114]
Trying to instal on my OpenBSD-adJ 7.2 it produces:
```
 % curl -H 'Cache-Control: no-cache' https://raw.git
hubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11827  100 11827    0     0  37183      0 --:--:-- --:--:-- --:--:-- 37309
fossas/fossa-cli crit platform openbsd/amd64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/fossas/fossa-cli/issues/new
```

**Comment by csasarak** [comment]
Hi,

We don't currently support OpenBSD and don't have plans to. 

I don't know of any specific reasons that it wouldn't build aside from OpenBSD not packaging GHC 9.0.2 compiler that we use. So if you are able to build it, it may work. We unfortunately won't really be able to provide you with much support for build or system related problems you experience later.
