### ISSUE TITLE
paket -> packet  may be confused

### ISSUE THREAD

**Issue by wjcIvan** [fossas/fossa-cli#1115]
Here is the code in the src/Types.hs.

`
135  PackageReferenceProjectType -> "packagereference" 

136  PackagesConfigProjectType -> "packagesconfig" 

137  PaketProjectType -> "packet"
`

Maybe it is the incorrect information.

**Comment by csasarak** [comment]
Thank you for reporting this, I will look into it. Could you please also describe the incorrect behaviors you're seeing with this along with the executable's version (`fossa --version`)? I want to be able to test and make sure I'm looking at the right problem.
