### ISSUE TITLE
Improve fallbacks for Go revision detection

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#113]
Right now, we give up on detecting Go revisions if they're not specified in the lockfile. We can improve on this approach by trying additional fallbacks before failure:

1. Checking whether the package exists within `vendor/`, and checking whether that folder is a git repository.
2. Checking whether the package exists within `$GOPATH`, and checking whether that folder is a git repository.
3. Looking up hashes with an external service, such as https://github.com/fossas/go-resolve.

**Comment by dchenk** [comment]
Now that the Go world seems to be converging on Go modules, we can achieve the desired results by leveraging the great features that have been added to the Go toolchain in the last couple versions, such as `go mod graph`.

Another needed fix:
```
if os.Getenv("GOPATH") == "" {
    return "", ErrNoGOPATH
}
gopath, err := filepath.Abs(os.Getenv("GOPATH"))
if err != nil {
    return "", errors.Wrap(err, "could not get absolute $GOPATH")
}
```
in `analyzers/golang/util.go` should rely on `go env GOPATH` instead.
