### ISSUE TITLE
Tests for PRs should not need `$FOSSA_API_KEY`

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#115]
The requirement for `$FOSSA_API_KEY` to upload an analysis causes both Circle CI and FOSSA to fail on PRs.

- Circle CI fails because tests run on PRs don't have access to `$FOSSA_API_KEY`, so any upload fails
- FOSSA fails because the failed upload prevents up from using provided builds

**Comment by ilikebits** [comment]
We need push-only API keys for this.

**Comment by ilikebits** [comment]
We now have support for "push-only" API keys, which only allow access to the API for uploading custom builds. Unfortunately, this currently is insufficient. We also use a variety of other APIs:

- The users API for determining organisation (for building custom locators).
- The licenses API for reporting.
- The issues API for testing.

**Comment by liftM** [comment]
Fixed.
