### ISSUE TITLE
autoconfiguration warning during initialization confusing

### ISSUE THREAD

**Issue by alvin-huang** [fossas/fossa-cli#118]
When running `fossa` without any arguments, the initialization throws the following warning:

```
⣾ Initializing... WARNING Warning during autoconfiguration: could not find Gradle binary or wrapper (try setting $GRADLE_BINARY)
CRITICAL No modules specified for analysis.
```
Is gradle set as the default builder to check? If not, this should probably be more generalized.

**Comment by alvin-huang** [comment]
Maybe this is related? https://github.com/fossas/fossa-cli/blob/master/docs/integrations/gradle.md#errors-during-fossa-init

**Comment by ilikebits** [comment]
Gradle isn't the default builder. All builders are run, but Gradle is the only one that complains.
