### ISSUE TITLE
Which go-bindata do you use?

### ISSUE THREAD

**Issue by alvin-huang** [fossas/fossa-cli#131]
https://github.com/fossas/fossa-cli/blob/cc1cc9a129d081a0584053c6ec1faffa31acdc91/Makefile#L16

I can fix the TODO here but I was wondering what go-bindata you use since the original owner of the repo deleted their account and there are multiple people rehosting it. ref: https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/

**Comment by ilikebits** [comment]
We currently use github.com/go-bindata/go-bindata, but I'm not totally sure whether it's better supported than github.com/jteuween/go-bindata. They seem similar enough, happy to go with whichever seems more stable to you (you guys probably have a lot more Go experience than us).
