### ISSUE TITLE
Add .fossaignore like option

### ISSUE THREAD

**Issue by jose-bigio** [fossas/fossa-cli#137]
### Request

Fossa Ignore option to blacklist projects

### Details

Currently the fossa cli supports the option for `fossa init`, but doesn't support an option to continue to update the fossa dot files. 

I'm not sure how the use of fossa will evolve nonetheless a desirable feature would be the ability to blacklist projects. 

### Examples

As an example there might be some tests that I run in a project, but I am not interested in the tests being tracked. 
Fossa init would discover the dependencies, but should allow me to blacklist them so that future `fossa init` runs don't re-add the packages that I am ignoring, so the feature could be something like a gitignore (fossaignore). 

Here's another proposed workflow for illustrative purposes: 

Or a workflow like
```
fossa init
blacklist projects
add new (sub)project
fossa update -> adds the new (sub)project and doesn't bring in the blacklisted projects
```

In this workflow I would imagine that you would check in the fossa dot files into source control.

**Comment by xizhao** [comment]
Proposal:

We can add an `ignore` flag to the module config to preserve what has been ignored in a previous `fossa init` + config.

**Comment by zlav** [comment]
Analysis target configuration now supports this feature https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md#analysis-target-configuration
