### ISSUE TITLE
Strange characters while running on Windows

### ISSUE THREAD

**Issue by joshuapetryk** [fossas/fossa-cli#152]
We're seeing weird console spew on Windows based systems (cmd and Powershell):

![image](https://user-images.githubusercontent.com/10408364/41196948-0692ed06-6c13-11e8-97fe-e24d173da63f.png)

I suspect this may be caused by the spinner.

**Comment by joshuapetryk** [comment]
I was informed we should try the --no-ansi option. Will try and report back.

**Comment by joshuapetryk** [comment]
`--no-ansi` doesn't appear to be a valid cli switch and did not resolve the issue.

**Comment by ilikebits** [comment]
`--no-ansi` is valid in `v0.7.0-beta.1`. Can you verify whether this still occurs for you?
