### ISSUE TITLE
Remove spinners

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#153]
We should replace the spinners with just a static loading icon.

They look pretty, but generate so much log garbage for things that don't support a "clear screen" option.

I like how https://zeit.co/dashboard formats their output.

**Comment by ilikebits** [comment]
A static icon would generate garbage too (just less).

Regardless, `--no-ansi` is coming in v0.7.0, and the spinner is disabled by default if `STDERR` is not a terminal.
