### ISSUE TITLE
Entry points should be more intuitive

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#16]
Right now, we expect entry point paths to be folders to the working directory of the project. We optionally allow this to be a file only if the file's name follows the convention of the build system (e.g. if it's `package.json` for `nodejs` or `build.sbt` for `sbt`). The code that handles this is in `//cmd/fossa/main.go` under `resolveModuleConfig`.

This is not particularly intuitive behaviour because users may expect to be able to provide the path to their custom-named manifest (for example, a Maven build manifest may be named `my-manifest.xml` rather than `pom.xml`). There are two approaches to this:

1. Require that entry points must be directories. This behaviour is consistent with the Go compiler's requirements.
2. Call `os.Stat` on the entry point. If the entry point is a file (presumably because it's a manifest), call `filepath.Dir` on the entry point.

Approach (2) adds complexity and convenience, approach (1) reduces complexity and improves predictability.

**Comment by xizhao** [comment]
We may want each module to be able to accept more configuration.  For instance, gradle has 2 dimensions that define an entry point:

 1. Where the `build.gradle` is found, which could be a non-standard manifest name
 2. What task to run for the build (default is `compile`, but the build has many entry points that will generate different results for artifact as well as any tools we can use to inspect it like `dependency:List`

**Comment by ilikebits** [comment]
Fixed in v0.7.0 UX.
