### ISSUE TITLE
Automatic debug logs + error reporting instructions

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#184]
Many errors and failures currently result in esoteric error output (such as panics). This needs to be much more ergonomic.

Requirements:

- All errors should have user-friendly messages.
- Debug logs should always be produced on error.
- Error messages should contain instructions for reporting an issue.

Implementation thoughts:

- We should _always_ stream debug logs to some temporary location, and possibly move those logs to the current directory on failure.
- We may want to develop our own application-specific `Error` struct that contains user instructions.
- The challenge here is representing wrapped errors, especially those coming from third-party dependencies. We need some notion of "cause", and some ergonomic way to display error messages and instructions given a "caused" error.

See also:

- #31

**Comment by zlav** [comment]
Closing in favor of an internal ticket.
