### ISSUE TITLE
`fossa help` command

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#185]
`go help <topic>` is an extremely useful command. Similarly, we may want to have a `fossa help <topic>` distinct from `fossa --help`, that specifically talks about concepts and topics (as opposed to command flags).

In an ideal world, we'd have manpages. In practice, most deployment environments may not have `man`.

Some topics that would be useful to document off the top of my head:

- FAQ and self-help: common errors and how to fix them (maybe this could be its own command as a wizard)
- FOSSA-specific concepts: locators, modules
- Module lifecycle: discovery, build, analysis
- Build system-specific concepts: common pitfalls, common building instructions, common flags

**Comment by zlav** [comment]
Closing in favor of an internal ticket.
