### ISSUE TITLE
Reporting on single dependencies

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#186]
A common feature request has been the ability to generate a FOSSA report or issue scan for a single dependency. The use case for this generally is:

1. Download a single package.
2. Check it for licensing issues.
3. Report whether it's okay to use this package.

This is NOT how FOSSA is intended to be used. Experience shows that this type of integration tends to lead to non-compliance for a variety of reasons:

1. Different builds (using the same package manifest!) can use different revisions of a package, and those revisions may have different licensing implications.
2. Empirically, we've seen that projects inevitably mis-report their licenses unless compliance checks run on _every build_.
3. You can already make single-dependency reports by making a dummy commit that only imports the new dependency.

That said, we see this feature request a lot. We might build it, given overwhelming demand.

**Comment by zlav** [comment]
The manual dependencies feature now supports this feature request https://github.com/fossas/fossa-cli/blob/master/docs/features/manual-dependencies.md
