### ISSUE TITLE
Config file v2

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#188]
This is a collection of ideas for the second iteration of the configuration file. This will be a breaking change.

- Remove the `fetcher` option. This confuses users who are not intimately familiar with FOSSA's internals. Instead, this should be `managed: true` or `provided: true` or `vcs: true` or `use-git-revision: true` (after all, only two values -- `git` and `custom` -- ever make any sense, so this may as well be boolean). Any of these would be easier to document and make better sense for users.
- Remove extraneous nesting. `analyze: module: [modules]` is redundant.
- Replace or deprecate `module.path` with `module.cwd` (to better reflect how it's used) or `module.target`. Often, having a separate `path` does not convey additional information.

**Comment by zlav** [comment]
Closing this issue due to incompatibility with the current FOSSA CLI roadmap which intends to remove configuration by default and only include necessary fields.
