### ISSUE TITLE
Add ability to specify a team for a given project

### ISSUE THREAD

**Issue by anuccio1** [fossas/fossa-cli#204]
**What kind of issue is this?**

- [ ] Question
- [ ] Bug report
- [x] Feature request
- [ ] Documentation (missing, incomplete, outdated)

**What is the issue?**

During the onboarding process, when an org is uploading several projects for the first time, it would be nice if they could specify the "Team" that this project should belong to in FOSSA

**If this is a bug report:**

The output of `fossa --version` is: 

<FOSSA_VERSION_HERE>

The output of `<fossa command> --debug` is:

<FOSSA_DEBUG_OUTPUT_HERE>

Your configuration file (usually `.fossa.yml`) is:

<FOSSA_CONFIG_HERE>

**Comment by liftM** [comment]
Fixed by #287.
