### ISSUE TITLE
Improve autoconfiguration

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#21]
In particular, we need to improve how we infer the project and revision. These don't currently happen correctly:

1. Calls to `git` should run in the directory of the module, not the working directory of the process.
2. There seems to be some bug where we don't correctly prefix `git+` to certain projects. My suspicion is an issue with special characters. We should have a strongly typed format for locators that we pass around, rather than inferring locator sections using delimited string.

**Comment by xizhao** [comment]
@ilikebits is this fixed?

**Comment by ilikebits** [comment]
We fixed this a while ago, although I don't remember the commits. It was during the refactor to the configuration system.
