### ISSUE TITLE
Add multi-environment integration tests

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#221]
We currently run integration tests in the [CLI test image](https://quay.io/repository/fossa/fossa-cli-test), which contains all build tools. Unfortunately, we sometimes see errors in cases where tools are _not_ installed, and these failure modes are not yet tested.

Some thoughts:

- One brute force approach is to create a different Docker image for testing each language. This sounds painful.
- We might be able to dynamically load and unload tools from the `$PATH`. I'm not sure how best to implement this. Maybe symlink and `$PATH`-setting trickery? This might affect tool behaviour.

See also: #182.

**Comment by ilikebits** [comment]
We also need to test for e.g. running inside folders that are NOT in git repositories.
