### ISSUE TITLE
`fossa test` with invalid API key generates cryptic error message

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [fossas/fossa-cli#226]
Hello I tried to use Fossa, and I obtain the following:

## Windows
```bash
.\fossa.exe test
CRITICAL Could not test revision: could not unmarshal JSON API response: json: cannot unmarshal object into Go value of type []fossa.User
```

## Travis CI
```bash
$ fossa test
⢿ Waiting for analysis to complete... CRITICAL Could not test revision: could not unmarshal JSON API response: json: cannot unmarshal object into Go value of type []fossa.User
```

Any idea on the issue ?

**Comment by liftM** [comment]
This looks like a problem with our backend. Can you run this with `--debug` and post the output? (You may want to redact parts of this output -- among other things, it will include your API key.)

**Comment by DEKHTIARJonathan** [comment]
The problem with the environment var setting the API Key. I think the error should be **a lot more** explicit. If you didn't tell me that debug is supposed to show the API Key I wouldn't have found the error...

**Comment by zlav** [comment]
Hello, this issue has been fixed in the latest version of the fossa-cli.
