### ISSUE TITLE
Support Go Modules (Go 1.11+, aka "vgo")

### ISSUE THREAD

**Issue by mitchellh** [fossas/fossa-cli#234]
**Is your feature request related to a problem? Please describe.**

We at HashiCorp are aggressively adopting Go modules. We use FOSSA scans in certain places and would like our CLI workflow to just work if possible.

**Describe the solution you'd like**

The CLI to automatically detect and support Go modules.

**Describe alternatives you've considered**

I've built a workaround `jq` script that works, but probably doesn't cover all cases. We've verified it against what `fossa` automatically generates with our previous `govendor` usage and we're seeing a more accurate list. We're still vetting this and iterating but it is a promising band-aid solution to start!

https://gist.github.com/mitchellh/72ccd9174897aeb65c46a6d6859919d6

Feel free to use this.

**Additional context**

Go modules are experimental in Go 1.11, but the Go core team has already promised backwards compatibility with `go.mod` and `go.sum` files and are encouraging people (especially library authors) to adopt this. To learn more: https://golang.org/cmd/go/#hdr-Preliminary_module_support

We've had our fair share of dependency issues and in limited tests we've found that modules in Go 1.11 are a good solution for us. We're beginning the transition throughout our projects now.

Note that Go modules also remove GOPATH, and the fossa CLI really dislikes if there is no GOPATH set. So thats also an issue that'll have to be resolved.

Thank you!

**Comment by liftM** [comment]
That hack is wild! I had no idea `jq` could use templates.

I'll take a look at getting to this during the week. We're still investigating the scope of this feature -- it may require non-trivial backend changes.

**Comment by mitchellh** [comment]
Yeah its pretty wild. Let me know if you have any questions or I can help in any way.

**Comment by zlav** [comment]
Hi @mitchellh we recently closed this issue and added support for GoModules. Fossa-cli will now by default recognize directories that use go modules and use the `go.mod` file to analyze the project. You shouldn't have to do anything other than update fossa-cli to the latest release for this to start working. If you have any questions let me know!
