### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by sudo-open-dev** [fossas/fossa-cli#236]
I am trying to build the CLI on my local machine, but facing difficulties.

Can you put together an installation guide or so? To make this process clear, so as to attract people from open source community to contribute and make the CLI better.

**Comment by liftM** [comment]
Our documentation for developers isn't great right now, but `make` will generally do what you need.

**Comment by zlav** [comment]
Closing because documentation has been added: https://github.com/fossas/fossa-cli/blob/master/docs/user-guide.md/#1-installation
