### ISSUE TITLE
GX Golang Dependencies Identified As Suspicious Package and GX Breaks Fossa

### ISSUE THREAD

**Issue by bonedaddy** [fossas/fossa-cli#263]
**Describe the bug**
Golang Dependencies Vendored Via [GX](https://github.com/whyrusleeping/gx) break fossa.
It breaks in two ways:
1) GX identified as suspicious:
```
WARNING Filtering out suspicious module: go-detect-race (vendor/gx/ipfs/Qmf7HqcW7LtCi1W8y2bdx2eJpze74jkbKqpByxgXikdbLF/go-detect-race)
WARNING Filtering out suspicious module: go-ctrlnet (vendor/gx/ipfs/QmfEZa44SyWfyXpkbVfi19H1QpY73DU6E5omK2HbKXwqR6/go-ctrlnet)
WARNING Filtering out suspicious module: go-multierror (vendor/gx/ipfs/QmfGQp6VVqdPCDyzEM6EGwMY74YPabTSEoQWHUxZuCSWj3/go-multierror)
⣷ Initializing... WARNING Filtering out suspicious module: murmur3 (vendor/gx/ipfs/QmfJHywXQu98UeZtGJBQrPAR6AtmDjjbe3qjTo9piXHPnx/murmur3)
WARNING Filtering out suspicious module: fsnotify (vendor/gx/ipfs/QmfNjggF4Pt6erqg3NDafD3MdvDHk1qqCVr8pL5hnPucS8/fsnotify)
```
2) Fails to resolve gx dependencies crashing fossa
```
⣟ Analyzing module (1/1): github.com/RTradeLtd/Temporal/cmd/temporal FATAL Could not analyze: could not resolve github.com/RTradeLtd/Temporal/vendor/gx/ipfs/QmS6mo1dPpHdYsVkm27BRZDLxpKBCiJKUH8fHX15XFfMez/go-ipfs-exchange-offline: no revision found for package name
```
**To Reproduce**
1. `go get -u -v github.com/RTradeLtd/Temporal`
2. `cd $GOPATH/src/github.com/RTradeLtd/Temporal`
3. `fossa -o`

**Expected behavior**
fossa should run properly 

**Debugging information**
Please provide the following:

1. For debug output see [this file](https://ipfs.io/ipfs/QmPyLkzj4wo6tg4r86ZytcwPATbgZeDKvc6rFN8Ngq5r1k), might take a few seconds to load
2. The output of `fossa --version`
```
fossa-cli version 0.7.7 (revision e874ec2891b456ea3689825b37c278b68301bdf0 compiled with go version go1.10.3 linux/amd64)
```
3. The project's configuration file (usually `.fossa.yml`)
```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: https://github.com/RTradeLtd/Temporal
analyze:
  modules:
  - name: github.com/RTradeLtd/Temporal/cmd/temporal
    type: go
    target: github.com/RTradeLtd/Temporal/cmd/temporal
    path: /home/solidity/go/src/github.com/RTradeLtd/Temporal/cmd/temporal
```
4. If possible, a minimal test case reproducing the bug (see temporal github)

**Environment (please complete the following information):**
 - OS:  Ubuntu 18.04 fork (Pop_OS!)

**Comment by liftM** [comment]
Thanks for the report! We don't support GX as a package manager, and have no immediate plans to. That said, PRs are welcome!

The analysis in the web app uses a different technique for revision resolution. We're continually improving our revision detection reliability.

**Comment by postables** [comment]
Any particular links to already existing supported package managers? Would help to figure out a plan of attack for gx support :grin:
