### ISSUE TITLE
nodejs fallback

### ISSUE THREAD

**Issue by microsoftly** [fossas/fossa-cli#282]
When analyzing a nodejs project, we should use the following analysis strategies, where the order of the list is the precedence. Should a method fail, we should move to the next level via automatic fallback before errorring

- [x] query build tool
  - [x] `npm ls`
  - [x] `yarn ls`
- [x] check `node_modules`
- [ ] lockfiles
  - [ ] `yarn.lock` 
  - [ ] `package-lock.json`
  - [ ] `npm-shrinkwrap.json`
- [ ] read manifest (failure here is okay)

**Comment by xizhao** [comment]
We also might want to validate output from npm or gate behavior based off npm version as different versions of npm actually have bugs and implementation issues.  Otherwise we might run into random fatal errors trying to reference data structures that don't exist.

**Comment by liftM** [comment]
This looks accurate. See also:

https://github.com/fossas/fossa-cli/blob/master/analyzers/nodejs/nodejs.go#L47-L59

(This may be outdated, but represented my thoughts at the time.)
