### ISSUE TITLE
Glide lock files should be able to prioritize repo field when looking at dependencies over name

### ISSUE THREAD

**Issue by zlav** [fossas/fossa-cli#303]
**Describe the solution you'd like**
Glide lock files only parse the name field currently when analyzing build information. In instances where the repo differs from the name there should be an option to target the repo.

**Comment by zlav** [comment]
@2ffs2nns

**Comment by zlav** [comment]
Context on Glide.lock configuration where repo field differs from name field: https://stackoverflow.com/questions/44802725/how-to-use-local-versions-of-glide-dependencies

**Comment by liftM** [comment]
Some notes:

- These packages will still show up as unresolved in FOSSA if the repositories are private.
- We need to normalise URLs (e.g. SSH) into valid Go package paths.
