### ISSUE TITLE
WARNING Could not get OrganizationID while constructing locator

### ISSUE THREAD

**Issue by grosser** [fossas/fossa-cli#321]
did not change our setup and suddenly it's failing with this error https://travis-ci.org/zendesk/samson/jobs/437513874

**Comment by microsoftly** [comment]
@grosser We're looking into the issue. Could you please provide your `.fossa.yml`?

**Comment by liftM** [comment]
This is probably related to #281 cc @zlav.

**Comment by microsoftly** [comment]
@grosser  could you retry the build?

**Comment by grosser** [comment]
`priority: low` since it's not a blocker, just failing on forks ... I guess this was the only PR we ever had that did not come from our base repo :(

```
WARNING Unrecognized locator
WARNING Unrecognized locator
FATAL Error during upload: you do not have permission to upload builds for this project
```

**Comment by grosser** [comment]
also can't retry now since the ref is gone ... and now the logs are gone too since I restarted it :(

**Comment by grosser** [comment]
yeah according to travis docs secrets are not shared with fork PRs ... which kinda makes sense ...
but the error message should be nicer ... like "Api key is missing" or so :)

**Comment by grosser** [comment]
... and analyze should `exit 1` when upload failed or key was not given

**Comment by grosser** [comment]
hmm it might already do the exit status, I think travis might continue if a step fails ... checking

**Comment by grosser** [comment]
FYI changing it to fail nicely and pass when using a foreign repository to make a PR
https://github.com/zendesk/samson/pull/2980

... that snipped might be nice for your readme in a travis section, since it's not very obvious :)

**Comment by liftM** [comment]
Closing in favor of #226.
