### ISSUE TITLE
Specify multiple build tags for Go analysis

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#341]
Go packages will bring in different dependencies depending on `GOOS` and `GOARCH`. This request is for use cases where users want their report to include a union of all dependencies for all combinations of build tags, OS, and architecture.

**Comment by dave-tucker** [comment]
Vndr might use [this list](https://github.com/LK4D4/vndr/blob/master/build/syslist.go#L7-L8) to ensure that all combinations of OS/Arch are taken in to account when computing dependencies.
