### ISSUE TITLE
Refactoring build uploads

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#343]
We want to defer the responsibility of fetcher type defining and locator definition/normalization to `fossa core`. 

If this change were in effect today, all cli uploaded builds would have a fetcher of `custom`. This means that fetcher definition in `.fossa.yml` should be removed.

Additionally, we should not attempt to normalize locators on uploads, rather we should supply the necessary fields to construct the locators for `fossa core` on each request

**Comment by microsoftly** [comment]
Proposed upload type:
```typescript
type BuildUploadQueryParams = {
  projectName: string;
  revision?: string;
  v: string;
  title: string;
  branch?: string;
  projectURL?: string;
  jiraProjectKey?: string;
  link?: string;
  team?: string;
};
```

**Comment by liftM** [comment]
I'm beginning to think we should add all of these to the body of the payload rather than just the query parameters. Our payload body is shaped weirdly and that's only because of legacy in the backend. My proposal:

```typescript
type Payload = {
  vcs: {
    type: 'git' | 'none'; // Detected VCS type
    reference: string; // VCS reference (branch or tag) name
  };
  project: {
    title: string; // Human-readable name
    id: string; // Project identifier, probably inferred from git remote origin
    url: string; // Project URL (provides that one link on the project page, I think)
    jira: string; // JIRA project key
    team: string; // FOSSA team
  };
  revision: {
    id: string; // Revision identifier, probably inferred from VCS revision hash
    link: string; // Arbitrary link for revision metadata (e.g. link back to CI)
  };
  meta: {
    v: string; // CLI version
  };
  analysis: Analysis; // Existing analysis payload
};
```

We should NOT do any processing of `project.id` -- the backend should be able to infer OrgID from the API key when it maps `project.id` to a project locator.

**Comment by microsoftly** [comment]
I agree, I like it

**Comment by sirandysaunders** [comment]
Save
