### ISSUE TITLE
Ergonomic errors

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#344]
## Problem

Our current error messages leave something to be desired. Some examples of bad error messages:

| Error | Root cause
|-|-
| `Failed to get some revisions: could not unmarshal JSON API response: json: cannot unmarshal object into Go value of type []fossa.Revision` | The user forgot to provide an API key.
| `Could not test revision: could not unmarshal JSON API response: json: cannot unmarshal object into Go value of type []fossa.User` | There was a bug in our request handling code.
| `Could not analyze: open subfoo/Podfile.lock: no such file or directory` | A nested module in a project was not built.
| `Could not analyze: fork/exec : no such file or directory` | A build tool was not found.
| `Could not analyze: could not get dependency list from Composer: fork/exec /usr/local/bin/composer: not a directory` | An old configuration file was parsed incorrectly.
| `Could not get OrganizationID while constructing locator` | The environment did not have the correct API key.
| `Unrecognized locator` | I have no idea, but this should definitely not happen.
| `Could not analyze: no revision found for package name` | The user's build was not correctly configured.
| `panic: runtime error: slice bounds out of range` | We didn't handle Windows line endings correctly (also happens on old configuration file parsing).

## Goals

These messages need to get a lot better.

1. A user should be able to understand what the problem is, and distinguish between a bug on our end vs. an incorrect configuration on their end.
2. Ideally, we should provide enough information that a user can resolve the issue on their own.
3. We should provide easy instructions for filing useful bug reports in case they need us to help.

### The error message UX

Here's a prototype of better error messages:

![2018-10-10-184908_1138x898_scrot](https://user-images.githubusercontent.com/2092654/46775715-367f5580-ccbd-11e8-8c4a-7f81eff52770.png)

### Types of errors

There are really 4 groups of errors:

1. The user has done something wrong (bad invocation, bad configuration file, wrong flags, etc.).
2. A module has something wrong with it (it's not built, required build tools are not available, etc.).
3. The system has done something wrong (out of memory, out of disk space, network failure, etc.)
4. There is a bug in the CLI.

These currently manifest in 3 different ways:

1. An error is returned: this is the ideal way to handle errors.
2. A `log.Fatal` occurs: this kind of error handling is very difficult to make consistent, and should be avoided overall. Unfortunately, we do this in a lot of places (especially in situations that should "never" occur).
3. A panic occurs: this happens especially in our parsing code. We must be able to gracefully handle panics.

### Design

To fix this, we'll need to add 3 kinds of error handling code:

1. At the top level, we'll need to add a `panic` handler using `defer` and then `recover`. This will handle all panics.
2. Within our own code, we'll return special `Error` structures that carry metadata for pretty-printing.
3. At the boundary with third-party code, we'll need to develop some kind of wrapping method.

### Open questions

The best way to handle chains of errors is not clear, especially since we want to pretty-print a useful and actionable error message.

- How do we wrap internal errors?
- How do we wrap external errors?
- When wrapping, how do we pretty-print chains of errors?

**Comment by zlav** [comment]
PR #462 extended the errors package to provide support for these ergonomic errors. Closing this issue as a result of that PR.
