### ISSUE TITLE
Maven `pom.xml` parsing

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#347]
Integration with Maven builds has historically been difficult for a combination of reasons:

- Maven is really hard to install and configure.
- Maven builds tend to be extremely custom and fragile.
- The user integrating the CLI tends not to be the person who actually wrote the build.

All this means that it's often very difficult to get `mvn ls` working correctly on a project. In these cases, we must be able to degrade gracefully. This probably means parsing Maven manifest files.

**Comment by dchenk** [comment]
Fixed in PR #449
