### ISSUE TITLE
Can fossa-cli run in a container?

### ISSUE THREAD

**Issue by yurishkuro** [fossas/fossa-cli#354]
**Describe the bug**

Not sure if this is a bug of expected behavior. I don't want to install fossa-cli on my laptop directly, so I tried to run it in a debian container.

**To Reproduce**
```shell
$ docker run -it -v `pwd`:/jaeger --rm debian /bin/bash
root@7f426dee4913:/# apt-get update
root@7f426dee4913:/# apt-get install curl
root@7f426dee4913:/# curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
root@7f426dee4913:/# cd /jaeger
root@7f426dee4913:/jaeger# fossa -o
⡿ Initializing... ^C
```

**Expected behavior**
I was expecting something to happen. Instead the "initializing" step was running for over 20min with no output.

**Environment (please complete the following information):**
 - OS: MacOS 10.13.6
- Docker CE 18.06.0

**Comment by microsoftly** [comment]
@yurishkuro could you send us your debug logs? You can find them at `/tmp/fossa-cli.*.log`?

Note: you redact sensitive fields if you post here or DM me (Matt Schwartz) in the community slack at https://slack.fossa.io/.

**Comment by yurishkuro** [comment]
I see from the logs that it keeps scanning. Turns out it just takes that long on the main Jaeger  repo. 

It also failed a bunch of time, turns out it needs additional dev tooling
```
⣯ Initializing... WARNING An error occurred during discovery: `go` not found, skipping searching for Go projects
⣷ Initializing... WARNING An error occurred during discovery: could not find Gradle projects: exec: "gradle": executable file not found in $PATH
```

**Comment by yurishkuro** [comment]
Is there a description of what other tooling fossa-cli needs on the machine?

**Comment by microsoftly** [comment]
We use various build tools in different environments (see https://github.com/fossas/fossa-cli/blob/master/docs/how-it-works.md) in order to analyze your project.

It looks like you need the build tools necessary to build `jaeger`. From looking at the public git, I can see that it's at the very least a `golang` project, so it requires `go` to be installed. We'd also recommend having `glide` (based on the public repo) installed, along with any additional package management tools that may be used.

**Comment by microsoftly** [comment]
@yurishkuro did that clear up the issues you were facing?

**Comment by yurishkuro** [comment]
I hadn't had a chance to try with an image that has Go etc. installed. 

Closing, since this doesn't appear to be an issue with fossa-cli itself.
