### ISSUE TITLE
"VCS type is not supported" even without trying to do an upload

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#358]
In an SVN repository, `fossa init` returns `FATAL Could not initialize: VCS type is not supported`.

This occurs because of a combination of unfortunate conditions + legacy code:

1. We attempt to open the VCS repository while setting up configuration in `package config` (we should really refactor this to be lazy i.e. to only open up the VCS repository when we need it to compute a value).
2. When detecting VCS repositories, we do a manual search for ancestor files with a sibling named like a metadata folder (e.g. `.svn`, `.hg`, `.git`, etc.).
3. Since we don't currently support reading revisions from non-Git repositories (e.g. Subversion), we return an `ErrUnsupportedVCS` when we find one.
4. We don't treat this `ErrUnsupportedVCS` as a special case in `package config`.

The way forward:

1. Fixing this bug is easy: we should avoid failing on `vcs.ErrUnsupportedVCS` in `package config` much like how we treat `vcs.ErrNoNearestVCS`.
2. Refactoring `package config` is a bit more involved. Ideally, we should avoid reading configuration files, opening VCS repositories, or otherwise having side effects until we need them to compute a value.
3. We should refactor `package vcs` to support non-Git repositories. This is probably going to be a large rewrite that touches many pieces of both `package vcs`, `package config`, and maybe `package analyzers/golang`. [Masterminds/vcs](https://github.com/Masterminds/vcs) seems like it offers what we need, although we might want to keep our existing file-walking logic.

Refactoring should probably be a separate PR (and maybe bug) from the fix. I'd size refactoring as an M or L.

**Comment by savehansson** [comment]
This seems to be a showstopper for my quick test. Is there a workaround?
