### ISSUE TITLE
FATAL Could not load build: timed out while waiting for build

### ISSUE THREAD

**Issue by grosser** [fossas/fossa-cli#369]
this has been failing for a few days now, maybe weeks

config https://github.com/zendesk/samson/blob/master/config/fossa.yml

result https://travis-ci.org/zendesk/samson/jobs/447893416

(PR: just adds `--debug` https://github.com/zendesk/samson/pull/3025)

**Comment by mattmckinstry** [comment]
Any word on this one?  We are seeing this too

**Comment by zlav** [comment]
This failure was related to an outage with FOSSA servers. Closing due to a fix which was implemented on FOSSA and inactivity.
