### ISSUE TITLE
"ERROR 30:8: unquoted '\'" on all commands

### ISSUE THREAD

**Issue by bdsoha** [fossas/fossa-cli#373]
**Describe the bug**
I successfully installed the latest version *0.7.4* on Mac and I'm able to run help *(`-h`)* commands. However, all other commands result in the following error:
```
> fossa -o
ERROR 30:8: unquoted '\' must be followed by new line
```

**Debugging information**

```
> fossa --version 
fossa-cli version 0.7.14 (revision 4821bdccd1ebffa72f69ae887a7b561803ba77b4 compiled with go version go1.11 linux/amd64)
```

**Environment:**
 - OS: MacOS Mojave
 - Are you running in CI?: no
 - Are you running in a Docker image?: No

**Comment by zlav** [comment]
Hi @bdsoha I believe the problem you are seeing is related to your git config file in reference to the issue seen here: https://github.com/src-d/go-git/issues/681. We will work on providing a fix but in the meantime you should be able to fix this by removing all `\`'s in `.git/config`.
