### ISSUE TITLE
Generated report produces inaccurate results

### ISSUE THREAD

**Issue by mgraczyk1** [fossas/fossa-cli#396]
In testing this, reports appear to be listing packages under several licenses that do not apply.

In one report, node-rdkafka is listed under BSD-2-Clause, BSD-2-Clause-NetBSD, BSD-3-Clause, MIT, Zlib and public-domain, however, only the MIT license applies.  

**Expected behavior**
I believe the result should list node-rdkafka only under the MIT license.

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag -- attached "api-connector-nodejs-mototrbo_FOSSA_DEBUG_LOG.txt"

2. The output of `fossa --version` -- fossa-cli version 0.7.15

3. The project's configuration file (usually `.fossa.yml`)
Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
Visit https://fossa.io to learn more
version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: git@git.avtecinc.com:Avtecinc/api-connector-nodejs-mototrbo.git
analyze:
  modules:
    name: .
    type: npm
    target: .
    path: .

4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)
Above example is a GitHub repo

**Environment (please complete the following information):**
 - OS: [e.g. Windows] -- Windows 10 Pro
 - Are you running in CI?: [e.g. No / Yes: CI_PROVIDER_NAME] -- Running directly using a script from Command Prompt and via Jenkins CI gives same results.
 - Are you running in a Docker image?: [e.g. No / Yes: DOCKER_IMAGE_NAME] -- No.

**Additional context**

Does node-rdkafka package fall under "Multiple-Licensed" and/or “permissive license” type?  Would this be why its showing up under all licenses in the report?

[api-connector-nodejs-mototrbo_FOSSA_DEBUG_LOG.txt](https://github.com/fossas/fossa-cli/files/2760381/api-connector-nodejs-mototrbo_FOSSA_DEBUG_LOG.txt)

**Comment by zlav** [comment]
@mgraczyk1 are you still seeing this issue? I closed a related issue, #389, right after you opened this one.

**Comment by zlav** [comment]
Closing this issue because `node-rdkafka` has many discovered licenses. This issue has surfaced a feature request to run a command such as `fossa report licenses --declared` to only return declared licenses for packages.
