### ISSUE TITLE
fossa test error messages are unclear

### ISSUE THREAD

**Issue by zlav** [fossas/fossa-cli#413]
**Describe the bug**
`fossa test` outputs `FATAL Could not load build: unknown task status:` when the command successfully connects to the fossa endpoint but is unable to successfully test. This can happen for a multitude of reasons which we should pass on to the user. 

**To Reproduce**
Run `fossa test` on a project that has not had a build uploaded yet.
Observe the response of `"message":"Not Found"` cause the error `unknown task status` to be output.

**Expected behavior**
`fossa test` handles the task status and outputs an appropriate command.

**Comment by zelahi** [comment]
Hi @zlav Apologies for not waiting but I was hoping to take a try at this issue.  I opened a PR if that is okay

**Comment by MerlinMason** [comment]
+1 for this, currently getting that error and no idea why.

**Comment by austince** [comment]
This seems to occur when the analysis is slow to actually kick off on the FOSSA servers - perhaps backoff of some sort is necessary?

**Comment by zlav** [comment]
Closing as this issue has not been seen for a while. I believe backend changes have fixed this issue.
