### ISSUE TITLE
Include timeouts for network calls and shell commands

### ISSUE THREAD

**Issue by zlav** [fossas/fossa-cli#433]
**Is your feature request related to a problem? Please describe.**
Most network calls and shell commands are currently allowed to run until failure. If the system fails to finish the network call or shell command then fossa will run indefinitely. This has been seen predominantly with gradle commands.

**Describe the solution you'd like**
A good solution would be giving the operator the ability to set a  customizable timeout that defaults to a reasonable amount of time and retries the command a set number of times if it is seen to fail. 

**Additional context**
CI environments are the most susceptible to these issues and run for unacceptable amounts of time if no timeout is implemented.

**Comment by renaud-vmg** [comment]
Yep. That'd be something we'd appreciate.

**Comment by zlav** [comment]
Fixed with PR #458 for gradle analyzer and option added for future use.
