### ISSUE TITLE
poetry support for python

### ISSUE THREAD

**Issue by sobolevn** [fossas/fossa-cli#451]
I would like to have `poetry` support. `poetry` is a packaging tool for `python` ecosystem. It uses `pyproject.toml` file to specify dependencies and `poetry.lock` to store locked versions.

https://poetry.eustace.io

**Comment by zlav** [comment]
Thanks for bringing this to our attention! Poetry looks like a great solution for Python dependency management. I am closing this issue and adding Poetry to Issue #189 which tracks all build tool support. This issue will be updated when support lands.
