### ISSUE TITLE
Gradle analyzer inaccurately determines the revision for requested versions

### ISSUE THREAD

**Issue by zlav** [fossas/fossa-cli#453]
**Describe the bug**
When `./gradlew <target>:dependencies` is run and we see a requested version the fossa-cli has difficulty creating a valid dependency locator.

**To Reproduce**
Mock gradle output:
```
default - Configuration for default artifacts.
+--- org.springframework.boot:spring-boot-starter -> 2.1.0.RELEASE
|    +--- org.springframework.boot:spring-boot:2.1.0.RELEASE
|    |    +--- org.springframework:spring-core:5.1.2.RELEASE
|    |    |    \--- org.springframework:spring-jcl:5.1.2.RELEASE
|    |    \--- org.springframework:spring-context:5.1.2.RELEASE
```

**Expected behavior**
Fossa should create an accurate locator from this dependency graph.

**Comment by dchenk** [comment]
Fixed in #454
