### ISSUE TITLE
Pricing for provided builds

### ISSUE THREAD

**Issue by lewisdaly** [fossas/fossa-cli#468]
I'm assessing Fossa for a set of open source projects and looking at integrating the provided builds into our CI workflow.

Is there a limit to the number of projects an account can use for provided builds? I saw that there is a limit of 5 projects to the free tier, but I seem to be able to keep adding more provided builds. Does the limit of 5 projects apply only to projects that are not built locally?

**Comment by zlav** [comment]
Hi, we do not enforce the number of builds for open source projects. If you have any further questions about Fossa's cloud product please direct them to support@fossa.com. Thank you for reaching out!
