### ISSUE TITLE
fossa analyze will result in FATAL Could not analyze: exit status 1 using Docker image

### ISSUE THREAD

**Issue by triffer** [fossas/fossa-cli#479]
**Describe the bug**
I can't run fossa analyze in a Docker container based on Ubuntu 18.04.

**To Reproduce**
1. Docker run image gradle:5.5
2. install fossa-fli using curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
3. execute fossa analyze using the API key
4. get error: Analyzing module (1/1): . FATAL Could not analyze: exit status 1

**Expected behavior**
Analyze executes without any problems.

**Debugging information**
Example project with fossa.yml https://github.com/triffer/fossa-cli-bug

debug out: https://github.com/triffer/fossa-cli-bug/blob/master/debugOut

**Environment (please complete the following information):**
 - OS: macOs
 - Are you running in CI?: No
 - Are you running in a Docker image?: Yes, gradle:5.5

**Additional context**
I can run fossa test without any problems.

**Comment by zlav** [comment]
Hi @triffer can you run `fossa analyze --debug` and send me the output?

**Comment by triffer** [comment]
Hi @zlav ,
the output is already in the git repository: debug out: https://github.com/triffer/fossa-cli-bug/blob/master/debugOut

**Comment by triffer** [comment]
I just tested the new release and I have another error now.
So it's the same repo to reproduce with the following steps:
- Start the docker container and mount my project
`docker run -it -v path/to/fossa-cli-bug/:/app gradle:5.5 /bin/bash`
- Install fossa-cli
`curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash`
- run `fossa test`with API key
- result is `FATAL Could not load build: unknown task status:  callers=[]`

Debug output can be found here: https://github.com/triffer/fossa-cli-bug/blob/master/20190724_debugOut

**Comment by triffer** [comment]
I'll close this, because I tested it using version 1.0.3 and everything is working fine. Thanks!
