### ISSUE TITLE
FATAL Error during upload: could not upload: API request timed out: Post 

### ISSUE THREAD

**Issue by cequintana** [fossas/fossa-cli#480]
**Describe the bug**
The POST API times out after 'fossa analyze' completes.

**To Reproduce**
Run fossa analyze

**Expected behavior**
Should get a report

Environment: Windows machine

$ fossa analyze
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Elasticsearch.Net\Elasticsearch.Net.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\FAKE\FAKE.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `AppServer\AppServer.csproj`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\DynamicInterop\DynamicInterop.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\xunit.core\xunit.core.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\NEST\NEST.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.AspNet.WebApi.Owin\Microsoft.AspNet.WebApi.Owin.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\xunit.runner.console\xunit.runner.console.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Owin\Owin.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Owin.Host.SystemWeb\Microsoft.Owin.Host.SystemWeb.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\xunit.analyzers\xunit.analyzers.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.AspNet.WebApi.Core\Microsoft.AspNet.WebApi.Core.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Tpl.Dataflow\Microsoft.Tpl.Dataflow.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Owin\Microsoft.Owin.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\R.NET\R.NET.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Topshelf.Serilog\Topshelf.Serilog.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Shyft.Auth\Shyft.Auth.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\StyleCop.Analyzers\StyleCop.Analyzers.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Topshelf\Topshelf.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\AsyncUsageAnalyzers\AsyncUsageAnalyzers.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\System.IdentityModel.Tokens.Jwt\System.IdentityModel.Tokens.Jwt.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `Common\Common.csproj`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.NETCore.Platforms\Microsoft.NETCore.Platforms.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Shyft.LoT.LineOfTherapyCore\Shyft.LoT.LineOfTherapyCore.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Thinktecture.IdentityModel.Hawk\Thinktecture.IdentityModel.Hawk.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\xunit\xunit.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `Worker\Worker.csproj`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\HangFire.Ninject\Hangfire.Ninject.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.IdentityModel.Protocol.Extensions\Microsoft.IdentityModel.Protocol.Extensions.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Owin.Security.Jwt\Microsoft.Owin.Security.Jwt.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Owin.Security.OAuth\Microsoft.Owin.Security.OAuth.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\Microsoft.Owin.Security\Microsoft.Owin.Security.nuspec`
WARNING Module does not appear to be built
WARNING No dependencies were found in `packages\DbExtensions\DbExtensions.nuspec`
WARNING Module does not appear to be built
WARNING Module does not appear to be built

FATAL Error during upload: could not upload: API request timed out: Post https://app.fossa.com/api/builds/custom?branch=master&locator=custom%2Bgit%40bitbucket.org%3Ashyftanalytics%2Fwhitehat-quantum.git%2418149145c56ffbfc6cbe7a7c0ecd9b7a287f2a04&managedBuild=true&title=git%40bitbucket.org%3Ashyftanalytics%2Fwhitehat-quantum.git&v=0.7.33: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by cequintana** [comment]
I figured out this was due to api key issue

**Comment by abhilashkasula** [comment]
Hi @cequintana I'm facing the same issue. Could you tell us what is the issue with api key and how can that be resolved?
