### ISSUE TITLE
Go modules in sub-directory of the repository root are not supported

### ISSUE THREAD

**Issue by kujenga** [fossas/fossa-cli#496]
**Describe the bug**

If you have a monorepo with a Go module in a sub-directory, the fossa command line tool errors. The only way that I was able to get this working was by modifying the source code of this tool.

I have a PR up that resolves this issue here: https://github.com/fossas/fossa-cli/pull/439, I'm hoping that making this issue raises the visibility of that PR so that I don't have to maintain the fork 🙂.

**To Reproduce**
1. Create a repository with a Go module in a subdirectory
2. Initialize fossa, then run `fossa analyze`
3. See error

**Expected behavior**
I would expect it to not error.

**Debugging information**

Here is a repository that reproduces the issue: https://github.com/kujenga/fossa-monorepo-bug

and the error output from `fossa analyze` in that repo:

```
⣯ Analyzing module (1/1): example.com/mymodule WARNING Could not determine whether module is built: could not run go list:  (exit status 1)
WARNING Module does not appear to be built
⡿ Analyzing module (1/1): example.com/mymodule FATAL Could not analyze: could not run go list:  (exit status 1)
```

**Environment (please complete the following information):**
 - OS: mac and linux
 - Are you running in CI?: This happens locally as well as in CI
 - Are you running in a Docker image?: No

**Additional context**

**Comment by cnr** [comment]
Thank you for the PR! Appreciate the recent rebase as well. Sorry it took so long to pick this up

Planning another release soon, so you should be able to retire your fork 🙏

**Comment by kujenga** [comment]
No worries, thank you so much!!!
