### ISSUE TITLE
Wrong alt location

### ISSUE THREAD

**Issue by Hongbo-Miao** [fossas/fossa-cli#536]
Sorry, I don't know which repo I should create this FOSSA issue.

I got a FOSSA pull request to add badge at https://github.com/Hongbo-Miao/hongbomiao.com/pull/199

As you can see the code it added is

```html
<a href="https://app.fossa.io/projects/git%2Bgithub.com%2FHongbo-Miao%2Fhongbomiao.com?ref=badge_shield" alt="FOSSA Status"><img src="https://app.fossa.io/api/projects/git%2Bgithub.com%2FHongbo-Miao%2Fhongbomiao.com.svg?type=shield"/></a>
```

Notice the `alt` is inside of `<a>` instead of `<img>`.

It should be

```html
<a href="https://app.fossa.io/projects/git%2Bgithub.com%2FHongbo-Miao%2Fhongbomiao.com?ref=badge_shield"><img src="https://app.fossa.io/api/projects/git%2Bgithub.com%2FHongbo-Miao%2Fhongbomiao.com.svg?type=shield" alt="FOSSA Status" /></a>
```

**Comment by zlav** [comment]
Thank you for filing this issue. The fossa bot is no longer actively submitting PRs and this issue should no longer be valid.
