### ISSUE TITLE
"Generating License Notices" example of `fossa report ...` is invalid

### ISSUE THREAD

**Issue by zdw** [fossas/fossa-cli#545]
**Describe the bug**
The docs specified for "Generating License Notices" are nonfunctional specified here in docs: https://github.com/fossas/fossa-cli#generating-license-notices

**To Reproduce**

Run example provided in docs:

```
$ fossa report --type licenses
Incorrect Usage. flag provided but not defined: -type

NAME:
   fossa-cli report - Generate reports

USAGE:
   fossa-cli report command [command options] [arguments...]

COMMANDS:
     dependencies  Generate dependencies report
     licenses      Generate licenses report

OPTIONS:
   --help, -h  show help
   
flag provided but not defined: -type
```

**Expected behavior**

That the example would work.

**Debugging information**

```
$ fossa -v
fossa-cli version 1.0.11 (revision 3e7c7b371e7a4b7b19e557a9a2b0d461f5c1276c compiled with go version go1.13.1 linux/amd64)
```

**Environment (please complete the following information):**
 
Linux/amd64

**Comment by aluttik** [comment]
Thanks for pointing this out @zdw, seems the docs are out of date. Instead try:
```
fossa report licenses
```

**Comment by RasikaUD** [comment]
fossa report licenses also doesn't work anymore @aluttik 
Only 
fossa report attribution works. Can we have the docs changed or modified to correct command so there is no confusion?
