### ISSUE TITLE
fossa init should have failure mode for automated runs

### ISSUE THREAD

**Issue by michaelcoyote** [fossas/fossa-cli#550]
**Is your feature request related to a problem? Please describe.**
When `fossa init` fails and no modules are found, the operation continues and runs until `fossa analyze` fails.  It seems strange to wait until analyze is run for the failure to happen, if no human would be available to fix the .fossa.yml file in a CI system.

**Describe the solution you'd like**
Would it be possible to give `fossa init` a "running in automation" flag where it would die if no modules were found? 

**Describe alternatives you've considered**
N/A

**Comment by zlav** [comment]
No longer applicable with FOSSA CLI v3
