### ISSUE TITLE
Go 1.14 vendor format change breaks analyze

### ISSUE THREAD

**Issue by Dean-Coakley** [fossas/fossa-cli#580]
**Describe the bug**
When using vendor directory with go 1.14 analyze fails.

I suspect this is due to new formatting changes of the go mod file in go 1.14.

```bash
INFO Analyzing module (1/1): project

WARNING Error reading dependencies from `cmd/main`: Could not run go list: Could not run `go list -m -json all` within path /home/travis/gopath/src/github.com/project: go list -m: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.) (exit status 1)

FATAL Could not analyze: Could not run go list: Could not run `go list -m -json all` within path /project: go list -m: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.) (exit status 1)
```

Snippet of problematic `vendor/modules.txt` changeset
```diff
+# github.com/onsi/ginkgo v1.10.1
+## explicit
+# github.com/onsi/gomega v1.7.0
+## explicit
 # github.com/pkg/errors v0.8.1
 github.com/pkg/errors
 # github.com/prometheus/client_golang v1.3.0
+## explicit
```

**Expected behavior**
Updating to go 1.14 to not change behavior

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
```
DEBUG done running callers=[/go/src/github.com/fossas/fossa-cli/exec/run.go:github.com/fossas/fossa-cli/exec.Run:60] stderr=go list -m: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.)
 stdout=
```
2. The output of `fossa --version`: 
```
fossa-cli version 1.0.20 (revision 39656fd214beaf9633765e8c614b6f24997532e7 compiled with go version go1.13.7 linux/amd64)
```

**Edit:** Tested again against 1.0.26, still present

**Environment (please complete the following information):**
 - OS: MacOS
 - Are you running in CI?: TravisCI
 - Are you running in a Docker image?: No

**Additional context**

**Comment by cnr** [comment]
This should be resolved now in 1.0.27! let me know if that doesn't resolve your issue
