### ISSUE TITLE
bug: Clicking on DCO is showing broken github link

### ISSUE THREAD

**Issue by nimish-gupta** [fossas/fossa-cli#586]
**Describe the bug**
When you click on the DCO link in the contribution guidelines it will show the broken GitHub link.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the DCO link under the License in https://github.com/fossas/fossa-cli/blob/master/.github/CONTRIBUTING.md
2. See GitHub broken link

**Expected behaviour**
Just link the proper DCO page, I think [this](https://github.com/fossas/fossa-cli/blob/master/DCO) one is the correct DCO page

**Extra**
Also, the behaviour is misspelt in the bug issue template, it is listed as `behavior`

**Comment by zlav** [comment]
This documentation is outdated, thank you for filing the ticket. We now have automation to check for broken links.
