### ISSUE TITLE
fossa analyze mvn:. avoiding jar test

### ISSUE THREAD

**Issue by darkprisco** [fossas/fossa-cli#593]
Hi all,
 I am trying to use `fossa analyze mvn:.` command but I am facing some problems during the usage.
In particular I would like to avoid the scanning of all the jars used during the test phase, so I want to scan only the ones used in the compile phase.

Maybe there is already the possibility to do that, so in that case sorry to have opened a new feature request.

So I would like to know if it is possible to make the `dependency:tree -Dscope=compile,` avoiding test jars.

Is there any way to do that ? something like:
` fossa analyze mvn:. cmd:"mvn dependency:tree -Dscope=compile" --revision ${var.version} `
Tks

**Comment by zlav** [comment]
Hi @darkprisco, I think that this option might help you out: https://github.com/fossas/fossa-cli/blob/master/docs/integrations/maven.md#cmd-string. 

You should be able to mandate that the cli runs `mvn dependency:tree -Dscope=compile` to get maven dependencies.

**Comment by ffatghub** [comment]
Hi @zlav @darkprisco 

I am trying to achieve the same thing (i.e. get dependencies only for scope=compile). Can you point me to the current manual page (link above is 404)? Or provide an example.

thanks
ciao

**Comment by zlav** [comment]
I am going to close this ticket as the issue initially created has been addressed.

@ffatghub we do not currently support scanning maven for only a specific dependency scope but I would encourage you to open another ticket with the issue if you are still seeing it in the latest version of the FOSSA CLI.
