### ISSUE TITLE
fossa test: unknown task status while waiting for FOSSA to analyze build

### ISSUE THREAD

**Issue by erickskrauch** [fossas/fossa-cli#596]
**Describe the bug**
`fossa test` outputs "ERROR: Could not test revision: Could not load build:: unknown task status while waiting for FOSSA to analyze build:". I can't understand the reason of the error.

**To Reproduce**
You can see this behavior on my project build:
https://travis-ci.org/github/elyby/chrly/jobs/677728406
Revision:
https://github.com/elyby/chrly/tree/f63d721747c88a7c9c0e5a2ddb12e096e86cd5fe

**Expected behavior**
Correct `test` behavior. Or a more detailed error message.

**Debugging information**
[.fossa.yml](https://github.com/elyby/chrly/blob/f63d721747c88a7c9c0e5a2ddb12e096e86cd5fe/.fossa.yml)
```
env FOSSA_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx fossa test --debug
INFO Waiting for analysis to complete... callers=[]
DEBUG making API request API key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx body= callers=[/go/src/github.com/fossas/fossa-cli/api/api.go:github.com/fossas/fossa-cli/api.MakeAPIRequest:91] endpoint={Scheme:https Opaque: User: Host:app.fossa.com Path:/api/cli/git+github.com:elyby/chrly$f63d721747c88a7c9c0e5a2ddb12e096e86cd5fe/latest_build RawPath:/api/cli/git+github.com:elyby%2Fchrly$f63d721747c88a7c9c0e5a2ddb12e096e86cd5fe/latest_build ForceQuery:false RawQuery: Fragment:} method=GET
DEBUG got API response callers=[/go/src/github.com/fossas/fossa-cli/api/api.go:github.com/fossas/fossa-cli/api.MakeAPIRequest:117] response={"uuid":"b65e64cd-dd24-4f8d-8e9e-255e3d754713","code":2004,"message":"Revision for locator (git+github.com:elyby/chrly$f63d721747c88a7c9c0e5a2ddb12e096e86cd5fe) was not found","name":"NotFoundError","httpStatusCode":404}
INFO Project status is . Waiting for FOSSA scan results... callers=[]
ERROR: Could not test revision: Could not load build:: unknown task status while waiting for FOSSA to analyze build: 
```

**Environment (please complete the following information):**
 - OS: Linux
 - Are you running in CI?: Yes / TravisCI
 - Are you running in a Docker image?: No

**Comment by zlav** [comment]
Hi @erickskrauch, we are pushing a fix for this issue that will be live next early next week. Let me know if you still see this issue after Tuesday 8/11.

**Comment by NarayanaReddy7** [comment]
@zlav I am seeing same error. Is this issue fixed ?

**Comment by mistercrunch** [comment]
@zlav this issue keeps coming back. We'd love to love fossa, but it's breaking our CI periodically.

**Comment by michaelcoyote** [comment]
Hi this is not a code issue.   I'd open a support ticket for this issue in the future (email to support@fossa.com will do it), however you are probably currently seeing this because FOSSA app is in database maintenance.  See https://fossa.statuspage.io/ for more information.

**Comment by zlav** [comment]
I am going to close this ticket as this issue should be addressed in the latest version of the FOSSA CLI. Please open another ticket if you continue to see this issue.
