### ISSUE TITLE
Misidentified licences

### ISSUE THREAD

**Issue by AlexAegis** [fossas/fossa-cli#603]
The fossa service misidentifies the licenses of certain repositories where a licence-name is mentioned in a code block. For example: https://github.com/jslicense/spdx-correct.js#readme
This particular repository is licenced under Apache-2, and is used to coerce the various spellings of licences to their official one. The example in the readme is interpreted as the projects licence.

I suggest not searching for licences in code blocks.

**Comment by rberrelleza** [comment]
I saw the same with https://github.com/spf13/cobra, due to the license strings mentioned in https://github.com/spf13/cobra/blob/master/cobra/cmd/license_agpl.go and similar

**Comment by zlav** [comment]
Hi @AlexAegis, thank you for bringing this up. The license scanning is not done within the fossa-cli itself. I would recommend opening a ticket with fossa support so that your issue can be handled properly. https://support.fossa.com/hc/en-us
