### ISSUE TITLE
Fossa init args either out of date or inaccurate

### ISSUE THREAD

**Issue by brphelps** [fossas/fossa-cli#604]
**Describe the bug**
https://github.com/fossas/fossa-cli/blob/master/docs/user-guide.md/#fossa-init indicates that option --overwrite exists and can overwrite the init'ed file. However, the parameter is not recognized when you execute fossa init.

**To Reproduce**
1. run fossa init --overwrite
2. See output: flag provided but not defined: -overwrite

**Expected behavior**
It works as documented.

**Environment (please complete the following information):**
 - OS: Tried on both windows and ubuntu 18.04
 - Are you running in CI?: No
 - Are you running in a Docker image?: No

**Comment by christopher-cudennec** [comment]
I can add that `fossa init --help` is misleading. It mentions `--option key:value` but this option seems to have no function at all. At least not the expected behaviour that the given options are added to the generated `.fossa.yml`.

Cheers!

**Comment by zlav** [comment]
Hi @brphelps, thank you for bringing this to our attention. I am not sure why the documentation is different from the provided options here.
