### ISSUE TITLE
Errors will happen when upgrading the libraries

### ISSUE THREAD

**Issue by KateGo520** [fossas/fossa-cli#609]
### github.com/urfave/cli  
-Latest Version: V2.2.0 (Latest commit d648edd on 6 Mar)
-Where did you use it: 
https://github.com/fossas/fossa-cli/search?q=urfave%2Fcli
-Detail: 
>[github.com/urfave/cli/go.mod](https://github.com/urfave/cli/blob/v2.2.0/go.mod#L7)
```
module github.com/urfave/cli/v2
go 1.11
require (
	github.com/BurntSushi/toml v0.3.1
	github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
	gopkg.in/yaml.v2 v2.2.2
) 
```

>[github.com/urfave/cli/docs.go](https://github.com/urfave/cli/blob/v2.2.0/docs.go#L11)
```
package cli
import (
	"github.com/cpuguy83/go-md2man/v2/md2man"
	…
) 
```
This problem was introduced since **_urfave/cli v1.22.1_** . Now you used the version [v1.20.0](https://github.com/fossas/fossa-cli/blob/master/Gopkg.toml#L59). If you try to upgrade  **urfave/cli** to version ** v1.22.1** and **above**, you will get an error--- **_no package exists at "github.com/cpuguy83/go-md2man/v2/md2man"_**

## I investigated the libraries'  (**urfave/cli >= v1.22.1**)  release information and found the root cause of this issue is that---- 
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the recent versions.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has migrated to Go Modules _must_ include the major version in the import path to reference any v2+ modules. For example,  Repo github.com/my/module migrated to Modules on version v3.x.y.  Then this repo should declare its module path with MAJOR version suffix "/v3"  (e.g., module `github.com/my/module/v3`), and its downstream project should use `"github.com/my/module/v3/mypkg"` to import this repo’s package.

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the general trend of ecosystem, If you want a better upgrade package experience, migrating to Go Modules is a good choice.

### 2. Keep using the dependency manage tool (like dep, glide, govendor, etc).

Because the import paths have different meanings between the projects adopting module mechanism and the non-module mechanism. 

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

If you prefer to use the dependencies manage tool (like dep, glide, govendor, etc), a textbook example provided by repo `github.com/moby/moby` can prevent this type of issues.
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the **/vN** subdirectory in the corresponding dependencies.
**This will help more downstream modules to work well with your package, otherwise they will be stuck in github.com/urfave/cli v1.22.4 .**

Do you plan to upgrade the libraries in near future?
Hope this issue report can help you ^_^
Thank you very much for your attention.

Best regards,
Kate

**Comment by KateGo520** [comment]
@zlav  @cnr   Could you help me review this issue? Thx :p

**Comment by zlav** [comment]
Hi @KateGo520, we do not have any plan to upgrade any libraries in the near future. If we decide to do that we will revisit this ticket. Thank you!

**Comment by KateGo520** [comment]
@zlav Thanks for your reply. This report is a warm prompt for you to prevent or combat this issue. Just let you know the problem if you upgrade this dependency in near future.

Hope this can help you.
Thanks again.
Kate
