### ISSUE TITLE
Golang Code Analysis Issue [Could not load analyzer: could not resolve command callers]

### ISSUE THREAD

**Issue by sandisan** [fossas/fossa-cli#613]
I am having issue with analyzer throwing error while analyzing Golang code "Could not load analyzer: could not resolve command callers". Here is the fossa.yml file

Folder Structure is web-test-ws/src/web-api. I am running the fossa cmd from web-test-ws.

version: 2
cli:
  server: https://fossa.gcso.cbre.com
  fetcher: custom
  project: [project-git-repo]
analyze:
  modules:
    - name: web-api
      type: go
      dir: src/web-api
      options:
        allow-unresolved: true

Here is the Command.  I am running the fossa cmd from web-test-ws.

export GOPATH=web-test-ws
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
export PATH=$PATH:/usr/local/bin
fossa init --include-all -e https://fossa.gcso.cbre.com
FOSSA_API_KEY=[API_KEY] fossa analyze --output --debug -T web

Here is the error:

WARNING Could not load analyzer: could not resolve command callers=[]
DEBUG analyzed: []module.Module{module.Module{Name:"web-api", Type:10, IsExecutable:false, Ignore:false, BuildTarget:"", Dir:"", Options:map[string]interface {}{"allow-unresolved":true}, Imports:[]pkg.Import(nil), Deps:map[pkg.ID]pkg.Package(nil)}} callers=[]
[{"Name":"eip-api","Type":"go","Manifest":"","Build":{"Artifact":"default","Context":null,"Succeeded":true,"Imports":null,"Dependencies":null}}]

**Comment by matfax** [comment]
I had the same issue. I got it working somehow. I set an absolute GOPATH explicitly (even with modules), I created all necessary GOPATH folders, built the project with go before analyzing, and applied `sudo chown -R $(id -u) /usr/local/bin/fossa`. Something did the trick.

**Comment by zlav** [comment]
Hello, we have overhauled our Golang analysis in the latest version of the FOSSA CLI. Please update to the latest version and let us know if you continue to have issues.
