### ISSUE TITLE
Support options for `fossa init`

### ISSUE THREAD

**Issue by christopher-cudennec** [fossas/fossa-cli#614]
**Is your feature request related to a problem? Please describe.**
I would like to integrate Fossa into our CI pipeline seamlessly. We have a lot of projects and it's a lot of work to create a ".fossy.yml" for every of these projects.

I now use a very ugly workaround in our CI pipeline. I first call "fossa init" and then append the missing lines to the configuration file using some bash commands.

**Describe the solution you'd like**
I'd like `fossa init` to support flag "--option" as described in "fossa init --help". I could then pass flags like "online:true" or "all-configurations:true".

**Describe alternatives you've considered**
Only alternative that I know of is creating ".fossa.yml" manually for every project.

**Additional context**

**Comment by zlav** [comment]
Hi @christopher-cudennec, this feedback is very helpful. We are making substantial changes to our CLI product that are focused around reducing the need to provide configuration. Once these changes are public, within the next 3 months, we will make sure you can access them and I would be happy to revisit this issue if it persists.

**Comment by christopher-cudennec** [comment]
Thanks @zlav ! We'll check it out definitely!

**Comment by zlav** [comment]
Hello, I am going to close this ticket as this issue has been addressed in the latest version of the FOSSA CLI.

**Comment by christopher-cudennec** [comment]
Yes, thanks. We don't need the .fossa.yml anymore. 👍
