### ISSUE TITLE
Could not initialize: could not get HEAD of git repository: reference not found

### ISSUE THREAD

**Issue by kotx** [fossas/fossa-cli#616]
When running `fossa.exe` the following error is printed:
```
could not get HEAD of git repository: reference not found
```
When running `fossa.exe init`, the following error is printed:
```
←[31mFATAL←[0m Could not initialize: could not get HEAD of git repository: reference not found
```

**To Reproduce**
1. Install fossa-cli via
```
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fossas/fossa-cli/master/install.ps1'))"
```
2. Run `fossa.exe` and `fossa.exe init`

**Expected behavior**
Fossa initializes a .fossa.yml configuration file. 

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag: IDENTICAL output.
2. The output of `fossa --version`: `fossa-cli version 1.0.30 (revision 09c02d600ff887c45e98ddee975a857b6e0fae6c compiled with go version go1.14.3 linux/amd64)`
3. The project's configuration file (usually `.fossa.yml`): N/A
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository): N/A?

**Environment (please complete the following information):**
 - OS: Windows
 - Are you running in CI?: No
 - Are you running in a Docker image?: No

**Additional context**
Fresh install of fossa-cli.

**Comment by zlav** [comment]
Hi @kotx, the fossa-cli's intended behavior here is to read information from a project's git configuration, if that does not exist the cli falls back to using the directory name.

Does the project you are attempting to scan have a git configuration at its root? Or is this a project without any VCS configuration?

**Comment by kotx** [comment]
It is a git repository with no changes committed.
