### ISSUE TITLE
Dedicated Github Action

### ISSUE THREAD

**Issue by shunkakinoki** [fossas/fossa-cli#617]
**Is your feature request related to a problem? Please describe.**
A dedicated github action would be really awesome!!! 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zlav** [comment]
Hi @shunkakinoki thanks for the suggestion! We are working on some substantial updates to the fossa-cli at the moment and we will keep this in mind.

**Comment by smorimoto** [comment]
I recently published the Action my team uses: https://github.com/fossa-contrib/fossa-action

**Comment by smorimoto** [comment]
I think we can close this.

**Comment by shunkakinoki** [comment]
Thanks for the actiion!!!

**Comment by smorimoto** [comment]
I can personally recommend it as it is already being used daily by our team.
