### ISSUE TITLE
fossa-cli fails to analyze go code in a subdirectory

### ISSUE THREAD

**Issue by rberrelleza** [fossas/fossa-cli#620]
**Describe the bug**
`fossa analyze` fails with the following error when my go code is in a subdirectory:
```
 Could not analyze: Could not analyze: no $GOPATH set
```

**To Reproduce**
1. `git clone https://github.com/rberrelleza/fossa-repo`
2. `cd fossa-repo`
3. `fossa analyze -o`

**Expected behavior**

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
2 .fossa-cli version 1.0.30
3. repro available at https://github.com/rberrelleza/fossa-repo

**Environment (please complete the following information):**
 - OS: MacOS
 - Are you running in CI?: No
 - Are you running in a Docker image?: No

**Additional context**

**Comment by rberrelleza** [comment]
Seems like there's no way to get `fossa analyze` to work if run from a folder that doesn't have the go.mod file?

**Comment by zlav** [comment]
Hi @rberrelleza, we recently rolled out a brand new version of the FOSSA CLI that should address the issue you are seeing. Let me know if you are still seeing this issue after updating.
