### ISSUE TITLE
False alarm for flexbuffer

### ISSUE THREAD

**Issue by Hongbo-Miao** [fossas/fossa-cli#622]
(Is this right place to create issue for https://fossa.com/ ?)

I got a false alarm for flexbuffer when I use https://fossa.com/ integrated with [my project](https://github.com/Hongbo-Miao/hongbomiao.com)

However, it does have a MIT license inside.
https://github.com/mercadolibre/flexbuffer-node/blob/master/LICENSE

![image](https://user-images.githubusercontent.com/3375461/89642716-e12b2400-d8e6-11ea-9324-bb0f642a2964.png)

**Comment by zlav** [comment]
Hi @Hongbo-Miao, I believe this is a server-side issue. The best way to support your request would be to open a ticket with fossa support at support.fossa.com.

**Comment by Hongbo-Miao** [comment]
Got it, thanks @zlav !
I was thinking fossa.com under hood is calling fossa-cli.
Yeah, I will create a ticket there.
