### ISSUE TITLE
Go analysis fails from within Docker containers

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#63]
Steps to reproduce:

1. Download alvin-huang/go-hello-world.
2. Download `fossa` v0.3.1.
3. Mount `go-hello-world` in its $GOPATH location within the `golang:1.10-stretch` container
4. Run `fossa analyze --modules go:.` from within the `go-hello-world` directory in the container.

Interestingly, `fossa` works if you build it from source from within the Docker container. I suspect this has to do with our usage of KyleBanks/depth for import analysis -- something about a difference between the environment's Go and the Go used to compile `fossa` is breaking things.

**Comment by ilikebits** [comment]
The easy way forward here seems to be parsing the output of `go list` instead of relying on KyleBanks/depth. I don't think we lose anything that way.

**Comment by xizhao** [comment]
I believe `go list` behavior may change depending on the version of `go` you're on; this was our default approach in FOSSA for a while, in `bom-cli`.

**Comment by ilikebits** [comment]
I reproduced this again by compiling `fossa` using `go1.10` and trying to analyse a project in a Docker container with `go1.9.4`. I suspect this is related to `depth`'s usage of `go/build` to analyse builds. Tracking upstream at KyleBanks/depth#15.

For now, we'll resolve this by changing our Go resolution strategy.
