### ISSUE TITLE
[Q] What is lockfile?

### ISSUE THREAD

**Issue by qingguee** [fossas/fossa-cli#630]
This is not a BUG, but questions. 
Version: v1.1.0

In https://github.com/fossas/fossa-cli/blob/5ec7a9e07e2d21529ceac17ea718b515abae764e/docs/integrations/golang.md#go

It mentioned about lockfile, but I don't have lockfile. So it's confusing. 
We are using "go mod vendor" now, I want to scan vendor folder for decencies for our code, but `modules-vendor: true` looks like not work. 
Can someone explain this? Or provide a guide for "go mod vendor" ? 

BRs

**Comment by zlav** [comment]
HI @qingguee, a lockfile is a file that specifies "pinned" versions of dependencies which ensures that every time your project is built, you will be downloading the same version of each dependency. The `lockfile` as specified was meant to support something like the dep package manager's concept of a lockfile, however, in the latest version of the FOSSA CLI, we have improved Golang support that should not require this configuration.
