### ISSUE TITLE
License false positive.

### ISSUE THREAD

**Issue by MatthewKhouzam** [fossas/fossa-cli#640]
**Describe the bug**
The license Eclipse Public License 2.0 with (Secondary) GNU General Public License, version 2 with the GNU Classpath Exception. This parses as "GPL only" which creates many false positives.

**To Reproduce**
1. have Fossa scan the following repo: https://www.npmjs.com/package/@theia/workspace

**Expected behavior**
It should return EPL or GPL. Not GPL only

**Debugging information**
Example failure in the wild:

https://github.com/theia-ide/theia-trace-extension/pull/218

**Environment (please complete the following information):**
 - OS: using Github CI
 - Are you running in CI?: Github.
 - Are you running in a Docker image?: No

**Comment by zlav** [comment]
Hi @MatthewKhouzam this has been fixed with our improved license scanner.
