### ISSUE TITLE
NPM: Uninstalled peerDependencies are "discovered" as installed with (LATEST) version

### ISSUE THREAD

**Issue by zenonhun** [fossas/fossa-cli#657]
**Describe the bug**
In our project we use nodejs (14.15), with NPM and package-lock.json.
Some of our deep dependencies have optional peerDependencies, which are not installed in the project.

However after analyzing the project, fossa-cli finds these dependencies as deep-dependency. For only these dependencies the
FOSSA UI shows (LATEST) as version
![image](https://user-images.githubusercontent.com/8852828/110980671-63d8fd80-8366-11eb-9eb3-ace8d6546263.png)

Every other dependency which are valid, the version is an exact one.
![image](https://user-images.githubusercontent.com/8852828/110980939-b2869780-8366-11eb-92af-80b14d06f4e5.png)

I would expect that the non-installed dependencies are not shown in the dependency list.

Continued to dig into the issue, here is the relevant section of the npm ls --json --production command:

```
"@org/base": {
      "version": "0.12.14",
      "from": "@org/base@^0.12.8",
      "resolved": "https://<internal.repo>/@org/base/-/@org/base-0.12.14.tgz",
      "problems": [
        "peer dep missing: d3@5.7.0, required by @org/vanilla@3.8.0",
        "peer dep missing: prismjs@1.15.0, required by @org/vanilla@3.8.0",
        "peer dep missing: dragula@3.7.2, required by @org/vanilla@3.8.0"
      ],
      "dependencies": {
        "@org/vanilla": {
          "version": "3.8.0",
          "from": "@org/vanilla@^3.6.0",
          "resolved": "https://<internal.repo>/@org/vanilla/-/@org/vanilla-3.8.0.tgz"
        },
        "d3": {
          "required": {
            "_id": "d3@5.7.0",
            "name": "d3",
            "version": "5.7.0",
            "peerMissing": [
              {
                "requiredBy": "@org/vanilla@3.8.0",
                "requires": "d3@5.7.0"
              }
            ],
            "dependencies": {}
          },
          "peerMissing": true
        },
        "prismjs": {
          "required": {
            "_id": "prismjs@1.15.0",
            "name": "prismjs",
            "version": "1.15.0",
            "peerMissing": [
              {
                "requiredBy": "@org/vanilla@3.8.0",
                "requires": "prismjs@1.15.0"
              }
            ],
            "dependencies": {}
          },
          "peerMissing": true
        },
        "dragula": {
          "required": {
            "_id": "dragula@3.7.2",
            "name": "dragula",
            "version": "3.7.2",
            "peerMissing": [
              {
                "requiredBy": "@org/vanilla@3.8.0",
                "requires": "dragula@3.7.2"
              }
            ],
            "dependencies": {}
          },
          "peerMissing": true
        }
      }
    },
```

After checking the nodejs analyzer, the issues seems obvious.
npm ls lists unmet peerDependencies under the relevant dependency, with "peerMissing": true attribute.

The analyzer shall filter out these dependencies from the final report.

**To Reproduce**
1. Create files '....'
2. Run command '....'
3. See error

**Expected behavior**

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
2. The output of `fossa --version`
3. The project's configuration file (usually `.fossa.yml`)
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Are you running in CI?: [e.g. No / Yes: CI_PROVIDER_NAME]
 - Are you running in a Docker image?: [e.g. No / Yes: DOCKER_IMAGE_NAME]

**Additional context**

**Comment by zenonhun** [comment]
I have added a proposed fix as pull request. Could you check it?

**Comment by zenonhun** [comment]
@zlav @scruffystuffs @liftM you look active members here. do you know how to have my PR reviewed or get it merged?

**Comment by scruffystuffs** [comment]
Short answer: This repo is in maintenance mode, and we recommend instead using our V2 analysis tool, which can be found [here](https://github.com/fossas/spectrometer).  This new tool is actively maintained, this one is less so.

Slightly longer answer:  This issue, while potentially valid, is not a critical issue.  There's an easy (though maybe not ideal) workaround in the UI: just ignore the dependencies.  Due to the burden of maintaining multiple tools, we are electing not to fix these non-critical issues in this tool (also, we will not accept the responsibility of maintaining them, even when the PR work is done for us).

I apologize for the late response on this, but we're going to close this issue, and the PR, as "Non-Critical".  If the issue still exists in the V2 tool, please file an issue there (we're much more active there).  Even though we aren't using it, thank you for taking the time to submit this issue and the fix for it.
