### ISSUE TITLE
ARM support missing in install.sh

### ISSUE THREAD

**Issue by pquerna** [fossas/fossa-cli#662]
**Is your feature request related to a problem? Please describe.**
ARM64 support is missing from install.sh

**Describe the solution you'd like**
ARM64 binaries are in the latest releases: https://github.com/fossas/fossa-cli/releases/tag/v1.1.7

But `https://github.com/fossas/fossa-cli/blob/master/install.sh` checks for limited architectures.  It might need to be regenerated?

**Comment by meghfossa** [comment]
Hi thanks for reporting. 

I recommend you migrate to using fossa v3, with `install-latest.sh` script, if you are not doing this already. If you not migrated to using v3, here is relevant documentation: https://github.com/fossas/fossa-cli/blob/master/docs/differences-from-v1.md#how-to-upgrade-to-fossa-3x

Latest `install-latest.sh` script (for fossa v3) will let you install fossa-cli on darwin/arm64 (m1) without an error. This was shipped in: https://github.com/fossas/fossa-cli/pull/753/files for fossa v3.x. 

You can try so with:
```bash
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
```

**Comment by KarstenSiemer** [comment]
@meghfossa what about linux arm64 though? Why is only darwin supported?
Linux arm64 support would be great

**Comment by zlav** [comment]
Hi @KarstenSiemer we currently only support Darwin arm64 to support the new Apple M1 laptops. We do not have plans to support Linux arm64 but we will keep this in mind and I will leave this ticket open.

**Comment by manifestori** [comment]
Any updates on this one @zlav ?

**Comment by rmkanda** [comment]
Still the same issue exists, 

```
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash -s -- v3.7.1 || exit 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12871  100 12871    0     0  11471      0  0:00:01  0:00:01 --:--:-- 11481
fossas/fossa-cli crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/fossas/fossa-cli/issues/new
```

**Comment by Sarim-Jalil** [comment]
Any update on Linux ARM64 support?

**Comment by mreichelt** [comment]
The missing linux/arm64 support of the fossa tool is the only dependency left that's blocking us from using arm64 docker images for our Android builds.

We would love to see fossa supporting this!

**Comment by csasarak** [comment]
Hi, I just wanted to update you. We now have made a release, [v3.9.32](https://github.com/fossas/fossa-cli/releases/tag/v3.9.32), which includes an ARM binary for Linux. You can get it from either that release page or using `install-latest.sh`. 

Technically, this isn't what this issue is asking for because it is asking for ARM support in `install.sh` which is used for FOSSA CLI version 1. We don't have plans to make any new releases for v1, however hopefully our support in v3 will be helpful.

**Comment by carocad** [comment]
> Hi, I just wanted to update you. We now have made a release, [v3.9.32](https://github.com/fossas/fossa-cli/releases/tag/v3.9.32), which includes an ARM binary for Linux. You can get it from either that release page or using `install-latest.sh`.
> 
> Technically, this isn't what this issue is asking for because it is asking for ARM support in `install.sh` which is used for FOSSA CLI version 1. We don't have plans to make any new releases for v1, however, so hopefully our support in v3 will be helpful.

Hey @csasarak ,
This is great !
We already migrated to v3 so for us the important thing was for the fossa cli to support linux/arm64 not particularly about v1.

Thanks for the effort :)
