### ISSUE TITLE
`fossa upload` report URLs should include the local branch

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#67]
When uploading and creating a URL, fossa-cli should detect the local branch instead of defaulting to master.  See it hardcoded here:

https://github.com/fossas/fossa-cli/blob/4bfa9c10a15449c4e1508e7348e9e3caffd30573/cmd/fossa/upload.go#L172

**Comment by ilikebits** [comment]
I'm not sure I understand what this means.

**Comment by ilikebits** [comment]
Fixed.
