### ISSUE TITLE
Deep dependencies are not found with NPM7+ (Nodejs16+)

### ISSUE THREAD

**Issue by zenonhun** [fossas/fossa-cli#672]
**Describe the bug**
In the latest nodejs (v16), the npm also upgraded to 7+.
In npm 7+ the behavior of `npm ls` is changed, now by default it lists only the direct dependencies.
To get the deep dependencies the `--all` option is required. 

https://docs.npmjs.com/cli/v7/commands/npm-ls

Fossa-cli uses the `npm ls --json --production` command to get the list of packages.
Now it shall be changed to add the `--all` option. In legacy npm versions it does nothing, so it is safe to add permanently.

**To Reproduce**
1. install nodejs 16.5.0
2. Run a fossa-cli analysis
3. See that it lists only direct dependencies

**Expected behavior**
Fossa-cli analysis shall find all direct and deep dependencies. 

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
2. The output of `fossa --version`
3. The project's configuration file (usually `.fossa.yml`)
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Are you running in CI?: [e.g. No / Yes: CI_PROVIDER_NAME]
 - Are you running in a Docker image?: [e.g. No / Yes: DOCKER_IMAGE_NAME]

**Additional context**

**Comment by zlav** [comment]
HI @zenonhun, the latest version of the FOSSA CLI should no longer have the issue you are listing here.
