### ISSUE TITLE
Long package names cause text overlay glitch in FOSSA badge

### ISSUE THREAD

**Issue by Xunnamius** [fossas/fossa-cli#676]
**Describe the bug**
One of my packages has a longer name. [This causes a glitch in the FOSSA badge when viewed on GitHub](https://github.com/Xunnamius/next-test-api-route-handler#documentation) and elsewhere.

![Screenshot_20210829_101151](https://user-images.githubusercontent.com/656017/131259370-a5bbbbdd-0edd-42ad-ab8f-e8dc937375d5.png)

**To reproduce**
1. Have a package with a long name
2. View the large-version badge for that package
3. See error

**Expected behavior**
Either the longer package name is clipped, perhaps with ellipses (i.e. `...`), or the commit ref is bumped to the next line.

**Comment by zlav** [comment]
Hi @Xunnamius, thank you for filing this ticket. Can you please open a ticket with support@fossa.com? They will be able to better support the issue you're seeing.
