### ISSUE TITLE
 No have dependencies for .net project!

### ISSUE THREAD

**Issue by jerviscui** [fossas/fossa-cli#678]
**Describe the bug**
I have use app.fossa.com scan a .net project from GitHub.
I confirm that the project is dependent.

But it show me there are 0 dependencies:
![image](https://user-images.githubusercontent.com/6396748/133597372-7394142d-b68f-492c-a49a-9b93ba163e37.png)
The three in the picture are the ones I added manually.

In GitHub Dependency graph can see the dependencies.
![image](https://user-images.githubusercontent.com/6396748/133597892-484bada7-4b6a-4247-9d65-5b66c4357085.png)

**Comment by zlav** [comment]
Hi @jerviscui, scanning a project on app.fossa.com uses a slightly different scanning method, for issues related to app.fossa.com I would recommend opening a support ticket in the UI. That said, the solution you will likely be suggested is to install the FOSSA CLI https://github.com/fossas/fossa-cli#getting-started. I would recommend you start here and open an issue if you have continued issues using the FOSSA CLI.
