### ISSUE TITLE
NPM dev dependencies are not filtered

### ISSUE THREAD

**Issue by zenonhun** [fossas/fossa-cli#696]
In our npm project fossa analyze lists all production and dev dependencies.
How can I make fossa analyze to find only production dependencies?

**Comment by thernstig** [comment]
@cnr @scruffystuffs I am using `fossa-cli version 3.0.12`. Is the intention that if I use `fossa analyze --output` the output contains items listed in `package.json` under `devDependencies`?

I pretty-printed the output in VS Code to explore. It seems there is no indication whatsoever in the output of what is a development (found under `devDependencies`) or production (found under `dependencies`) dependency.

So how could sending the results to the backend even know to not publish the development dependencies?

**Comment by thernstig** [comment]
@meghfossa I am still experiencing an issue with latest fossa cli version 3 finding certain development packages. One example (I have a clean package.json with just this package in it):

```json
{
  "name": "foo",
  "version": "0.0.0",
  "private": true,
  "license": "UNLICENSED",
  "type": "module",
  "devDependencies": {
    "webpack": "4.42.1"
  }
}
```

It will find the two deep dependencies `@webassemblyjs/ast` and `@webassemblyjs/helper-code-frame` for some reason.

**Comment by thernstig** [comment]
Amazing, this was reported over 9 months ago and it is **still** a problem.

**Comment by wochinge** [comment]
@csasarak This is still happening. Can you help out, please?
