### ISSUE TITLE
Security is not enabled

### ISSUE THREAD

**Issue by PiffPaffM** [fossas/fossa-cli#726]
Hello Fossa team,

I am running the fossa analyze command and was wondering if I can limit it to dependency checking. I get an error that Security is for our account is not enabled which is true. I could not find any option.

Thanks for your support

**Comment by kitified** [comment]
Hi @PiffPaffM!

Will you please give us the command you're running and the exact output you're getting?

**Comment by PiffPaffM** [comment]
@kitified thanks for coming back to me! Here the command:

`export FOSSA_API_KEY=<api-key>`
`fossa container analyze deepset/haystack-cpu:latest`

Output:
`message\":\"Security is not enabled for your organization.\"`

**Comment by Serubin** [comment]
Hi @PiffPaffM. Unfortunately, we dont support container scanning without our security product. If you want to trial security and container scanning feel free to shoot us an email at support@fossa.com.

Sorry we dont support this use case straight away, this may change in the future!
