### ISSUE TITLE
fossas/fossa-cli crit platform darwin/arm64 is not supported

### ISSUE THREAD

**Issue by niryi** [fossas/fossa-cli#743]
fossas/fossa-cli crit platform darwin/arm64 is not supported

**Comment by meghfossa** [comment]
Latest `install-latest.sh` script will let you install fossa-cli on m1 without an error. This was shipped in: https://github.com/fossas/fossa-cli/pull/753/files.

You can try it so with: 
```
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
```

I'm closing this ticket for now (feel free to create new ticket if you are running into this again).
