### ISSUE TITLE
Performance: Skip finding projects that are not of interest

### ISSUE THREAD

**Issue by thernstig** [fossas/fossa-cli#750]
The process of the fossa-cli is to first find all projects, and then to later analyze them according to the targets specified in `.fossa.yml`. But the part of finding projects (seen below) is taking an awfully lot of time. This is problematic in CI where the resources might be scarce:

```sh
~/code/projectA (fossav3)> fossa analyze --config .fossa.yml --output
[ 26 Waiting / 8 Running / 1 Completed ]
[TASK 1] Bundler > Finding projects > Walking the filetree
[TASK 2] Cabal > Finding projects > Walking the filetree
[TASK 3] Cargo > Finding projects > Walking the filetree
[TASK 4] Cocoapods > Finding projects > Walking the filetree
[TASK 5] Carthage > Finding projects > Walking the filetree
[TASK 6] Swift > Finding swift package projects > Walking the filetree
[TASK 7] Stack > Finding projects > Walking the filetree
[TASK 8] Setuptools > Finding projects > Walking the filetree
```

In most projects, they might only use one or two package managers. For example one project might just use `npm`.
In these cases it makes no sense for fossa-cli to find projects if you have a config like:

```yaml
version: 3

targets:
  only:
    - type: npm
      path: server/
```

It would be very cool if the actual _Finding projects_ part could:

1. Be allowed to find only certain target types such as `npm` 
2. Or even better, make sure the actual _Finding projects_ part only honors what is defined in the only section in `.fossa.yml`.

These improvements should save a lot of time spent in CI and resources used since it will significantly speed up the project discovery process.

**Comment by zlav** [comment]
Hi @thernstig we have fixed this issue in the latest FOSSA CLI release. We now honor the target restrictions listed in `.fossa.yml` during the project discovery phase.
