### ISSUE TITLE
Output flag should intake a value

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#8]
The `-o` flags behavior should perform as follows:

 1. If a param is specified i.e. `fossa -o output.json`, it should write to the output file.
 2. If a the flag is run alone with no param i.e. `fossa -o` it should write to stdout

**Comment by ilikebits** [comment]
Disagree. `fossa -o > output.json`. We should be writing interactive output (e.g. progress messages) to `stderr`.
