### ISSUE TITLE
Check for `sbt` required plugin and install them if missing

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#90]
We can install it in the global `plugins.sbt` at `~/.sbt/{VERSION}/plugins/plugins.sbt`

`addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")`

https://github.com/jrudolph/sbt-dependency-graph

**Comment by ilikebits** [comment]
I don't think we should automatically install them, but the error message here should be more informative.
