### ISSUE TITLE
How could I download the custom csv file?

### ISSUE THREAD

**Issue by wooshifu** [fossas/fossa-cli#914]
I am using fossa deployed on my company server. And now I want to download the report csv file, I found the url is `https://substitute-with-my-company-domain.com/projects/custom%2b1%2fA3ToolKit_-v1.1-7Apr2022/refs/branch/master/e7f02681bb72dc8fb87abfc3ad79be360ed6f30b`, and then I use postman to download the file, but the response is not the csv file I wanted, but the html webpage. see following pictures for more details. So my question is how could I download the csv file.
![1301650618847_ pic](https://user-images.githubusercontent.com/8529077/164677149-7b60dc41-fbef-453e-a42f-4d1850875c8f.jpg)
![1311650618974_ pic](https://user-images.githubusercontent.com/8529077/164677155-ea45e6b9-f038-4fdb-b028-7fe9de3f3cfd.jpg)
![1321650619002_ pic](https://user-images.githubusercontent.com/8529077/164677166-82f0dd07-2d97-4b14-85c1-5c6181e0cb8b.jpg)

**Comment by zlav** [comment]
Hi @wooshifu, I'm not entirely sure if this is something we support right now. Can you open a ticket with support@fossa.com? They will be able to better support you.
