### ISSUE TITLE
The results are different in Windows and Linux

### ISSUE THREAD

**Issue by GudaoFQ** [fossas/fossa-cli#967]
I downloaded fossa_3.3_windows_AMd64. zip and fossa_3.3_linux_amd64. zip from the Releases provided in the project; However, when I tested the same Java project on Windows and Linux, I found that they got different results. I then built the project through the `mvn dependency :tree` command and found that this was true in Linux, but much missing in Windows.
[WindowsAndLinux-Results.md](https://github.com/fossas/fossa-cli/files/8859647/WindowsAndLinux-Results.md)

**Comment by scruffystuffs** [comment]
It seems that the issue is that `mvn dependency :tree` is not working on your windows system, rather than there being some platform-specific bug (although that may be the underlying cause).  For more assistance on this issue, please contact us for support directly at https://support.fossa.com/.

**Comment by GudaoFQ** [comment]
Okay, thank you. I downloaded the newly released cli: v3.3.5, and now I can view the logs. I have asked a question on https://support.fossa.com/
